# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 22:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmproduct',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmproduct',
            name='price_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crmproduct',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crmproduct',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 2, 22, 58, 32, 84736)),
        ),
        migrations.AlterField(
            model_name='product',
            name='list_price',
            field=models.FloatField(default=0),
        ),
    ]
